[project]
name = "gaokao"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "curl-cffi>=0.12.0",
    "loguru>=0.7.3",
    "pymongo>=4.13.2",
    "requests>=2.32.4",
    "tenacity>=9.1.2",
]
